name: Compile and deploy to server
on:
  workflow_dispatch:
    inputs:
      copy-package-json:
        type: boolean
        description: Whether to copy package.json and package-lock.json into the server.
        default: false

jobs:
  compile-and-deploy:
    name: Compile and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js 18
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Compile files
        run: npm run build
      - name: Copy important files to ./dist
        run: |
          mkdir -p ./dist/src
          cp -r ./src/views ./dist/src/
          cp -r ./public ./dist/
      - name: Remove db_migrate from ./dist
        run: |
          rm -rf ./dist/db_migrate
      - name: Copy package.json and package-lock.json to ./dist
        run: |
          cp package.json ./dist
          cp package-lock.json ./dist
        if: github.event.inputs.copy-package-json == 'true'
      - name: List files in ./
        run: |
          ls ./
      - name: List files in ./dist
        run: |
          ls ./dist
      - name: Copy files to remote
        run: |
          mkdir -v -m 700 $HOME/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > $HOME/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 400 $HOME/.ssh/id_ed25519
          scp -i {{ $HOME/.ssh/id_ed25519 }} -r ./dist ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_SERVER_DEPLOYMENT_PATH }}
